c=1;
[music,fs]=audioread('music1.wav');
music=music(:,1);%变为单声道信号分析
L=length(music);
figure;
subplot(4,1,1);
plot(0:L-1,music);%打印原始信号
title('原始信号时域波形');xlabel('n');ylabel('x(n)');
Fftmusic=fft(music,L);
subplot(4,1,3);
plot(0:L-1,abs(Fftmusic));%打印频谱
title('原始信号频谱');xlabel('k');ylabel('X(k)');
%{
将模和相角分开
模变为整型数，以便LSB脚本中的bitset函数处理
%}
absfft=abs(Fftmusic);anglefft=angle(Fftmusic);
intabsfft=round(absfft*c);
img=imread('test.bmp');%读取图片文件并得到需要隐藏的序列
dataimg=rgb2gray(img);%考虑到图片特点，将图片转成灰度图的二维数组以缩减大小
szdataimg=size(dataimg);
writedata=dataimg(:);%需要隐藏的序列
hidintabsfft=LSB(szdataimg,writedata,intabsfft);
%已经加入了隐藏信息，之后需要将其变换回浮点数并组合成复数进行IFFT
hidabsfft=double(hidintabsfft);hidabsfft=hidabsfft/c;
hidfft=hidabsfft.*exp(anglefft*1i);
musicap=ifft(hidfft);
subplot(4,1,2);
plot(0:L-1,real(musicap));
title('带有隐藏信息信号时域波形');xlabel('n');ylabel('x(n)');
subplot(4,1,4);
plot(0:L-1,abs(hidfft));
title('带有隐藏信息信号频谱');xlabel('k');ylabel('X(k)');
fname='music_with_secret.wav';
audiowrite(fname,real(musicap),44100);
fileIDkey=fopen('key.bin','w');%虚部保存为密钥文件，解密时必要
fwrite(fileIDkey,imag(musicap),'double');
fclose(fileIDkey);
